### ISSUE TITLE
Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by MobileAppVault** [b-tiwari/CRNAExpoTSExample#2]
Hi,

Many thanks for your nice article!

Getting the following error with your configuration and `yarn test`.  

```
FAIL  src/App.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'Component' of undefined

      4 | export default class App extends React.Component {
      5 |   public render() {
    > 6 |     return (
      7 |       <View style={styles.container}>
      8 |         <Text>Open up App.js to start working on your app!</Text>
      9 |         <Text>Changes you make will automatically reload.</Text>

      at Object.<anonymous> (src/App.tsx:6:34)
      at Object.<anonymous> (src/App.test.tsx:5:15)
```

Many Thanks,
Marcus

**Comment by onsta** [comment]
Hi Marcus, 

try to clone the example and run it. It should be OK. And also try to compare it to your code. 

For me downgrading to "ts-jest": "^22.4.2" solved the problem as I was using 23 before.

Best Ondrej.
